version: '3.5'
services:
  tf-runtime:
    image: tensorflow/tensorflow:1.5.0-py3
    volumes:
      - type: bind
        source: .
        target: /notebooks/tf-learning
    command: /run_jupyter.sh --NotebookApp.token='' --allow-root
    ports:
      - "8888:8888"
      - "6006:6006"
    environment:
      - SHELL=/bin/bash
